{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "developer_query = \n",
    "\"\"\"\n",
    "{\n",
    "  user(login: \"josepholasoji\") {\n",
    "    name\n",
    "    email\n",
    "    followers {\n",
    "      totalCount\n",
    "    }\n",
    "    mycontributedprojects: repositories(first: 1, affiliations: COLLABORATOR) {\n",
    "      nodes {\n",
    "        name\n",
    "        description\n",
    "        createdAt\n",
    "        forkCount\n",
    "        hasProjectsEnabled\n",
    "        isDisabled\n",
    "        updatedAt\n",
    "        commits: object(expression: \"master\") {\n",
    "          ... on Commit {\n",
    "            history(first: 100, author: {emails: [\"josepholasoji@gmail.com\"]}) {\n",
    "              edges {\n",
    "                node {\n",
    "                  additions\n",
    "                  deletions\n",
    "                  comments {\n",
    "                    totalCount\n",
    "                  }\n",
    "                  author {\n",
    "                    email\n",
    "                    name\n",
    "                    date\n",
    "                  }\n",
    "                }\n",
    "              }\n",
    "              totalCount\n",
    "            }\n",
    "          }\n",
    "        }\n",
    "        releases {\n",
    "          totalCount\n",
    "        }\n",
    "        primaryLanguage {\n",
    "          name\n",
    "        }\n",
    "        languages(first: 100) {\n",
    "          nodes {\n",
    "            name\n",
    "          }\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "    myprojects: repositories(first: 2, affiliations: OWNER) {\n",
    "      nodes {\n",
    "        name\n",
    "        description\n",
    "        createdAt\n",
    "        forkCount\n",
    "        hasProjectsEnabled\n",
    "        isDisabled\n",
    "        updatedAt\n",
    "        commits: object(expression: \"master\") {\n",
    "          ... on Commit {\n",
    "            history(first: 100, author: {emails: [\"josepholasoji@gmail.com\"]}) {\n",
    "              edges {\n",
    "                node {\n",
    "                  additions\n",
    "                  deletions\n",
    "                  comments {\n",
    "                    totalCount\n",
    "                  }\n",
    "                  author {\n",
    "                    email\n",
    "                    name\n",
    "                    date\n",
    "                  }\n",
    "                }\n",
    "              }\n",
    "              totalCount\n",
    "            }\n",
    "          }\n",
    "        }\n",
    "        releases {\n",
    "          totalCount\n",
    "        }\n",
    "        primaryLanguage {\n",
    "          name\n",
    "        }\n",
    "        languages(first: 100) {\n",
    "          nodes {\n",
    "            name\n",
    "          }\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "\"\"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
